name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Make compiler executable
      run: chmod +x ./tools/tweego/tweego-linux-x64

    - name: Build project
      run: ./tools/tweego/tweego-linux-x64 -o index.html  ./src

    - name: List build output
      run: ls -la .

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: gh-pages
        clean: true
